package com.example.demomultipledb.persondb;
import lombok.*;

import javax.persistence.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Builder
@Entity
@Table(name = "my_person")
public class Person {

    /**
     * Hibernate converts all the camel cases into two words separated by underscore
     * Hibernate convert all the uppercase into lowercase
     */
    private static int counter;

    // myFirstName --> my_first_name

    /**
     * AUTO -
     create table person(id int primary key, ....)
     insert into person(id, name, ...) VALUES (<ID>, <name>, ....)
     * IDENTITY -
     create table person(id int primary key auto_increment, ..... )
     insert into person(name, ...) VALUES (<name>, ...)
     **/

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;  // automatically generated by server |  FE need not send this

    @Column(name = "first_name", length = 30)
    private String firstName;
    private String lastName;

    private Integer age;
    private String dob;

    @Transient
    private String countryCode;
}

